services:
  - type: web
    name: cline-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: API_KEY
        generateValue: true
      - key: DEFAULT_LLM_PROVIDER
        value: anthropic
      - key: DEFAULT_MODEL
        value: claude-3-5-sonnet-20241022
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX
        value: 100
      - key: LOG_LEVEL
        value: info
      # Set these manually in Render dashboard for security
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false